Add support for responsive maps thru a 'responsive' property and a us…
btmills/react-datamaps pull request #12
Opened 2016-12-04 19:57 UTC by eitanp461

…ag example

2016-12-10 03:50 UTC, btmills requested changes
This is great, thank you! Just one bit of cleanup, and then I think this is ready to go.

2016-12-10 03:50 UTC, btmills commented on src/datamap.jsx
> +	} = this.props;
It looks like the whitespace from here down got messed up. Can you fix that?

2016-12-10 21:28 UTC, eitanp461 commented on src/datamap.jsx
> +	} = this.props;
No problem. VSCode has some issues with spread operator

2016-12-11 16:39 UTC, btmills approved these changes
LGTM, thanks! I'll get a release out shortly :ship:

2016-12-11 16:40 UTC, merged

2016-12-11 17:03 UTC, btmills commented
Released as [v0.3.0](https://github.com/btmills/react-datamaps/releases/tag/v0.3.0) :shipit:

2016-12-11 21:23 UTC, eitanp461 commented
Thanks for merging this change and creating this module :)